FROM centos:7
RUN yum -y update \
&& yum install -y wget unzip perl git make gcc-c++ glivc-static zlib1g-dev zlib-devel gcc \
&& cd /usr/local/bin \

&& wget https://github.com/alexdobin/STAR/archive/2.7.10a.tar.gz \
&& tar -xzf 2.7.10a.tar.gz \
&& rm 2.7.10a.tar.gz \
&& cd STAR-2.7.10a \
&& cd source \
&& make STAR \
&& chmod 755 STAR \
&& cd ../../ \
&& mv STAR-2.7.10a/source/STAR . \
&& rm -rf STAR-2.7.10a/

ENTRYPOINT ["/usr/local/bin/STAR"]