FROM ncbi/sra-tools:latest
RUN echo -e "http://nl.alpinelinux.org/alpine/v3.5/main\nhttp://nl.alpinelinux.org/alpine/v3.5/community" > /etc/apk/repositories \
&& apk update \
&& apk upgrade \
&& apk add bash